# Generated by Django 4.2.3 on 2024-05-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VEN_NAME', models.CharField(max_length=255)),
                ('EBELN', models.CharField(max_length=255)),
                ('TXZ01', models.TextField()),
                ('MENGE_PO', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
