# Generated by Django 4.2.3 on 2024-05-23 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inte', '0002_purchaseorder_delete_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PurchaseOrder',
            new_name='raghul',
        ),
    ]
