# Generated by Django 4.2.3 on 2024-05-23 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inte', '0003_rename_purchaseorder_raghul'),
    ]

    operations = [
        migrations.AddField(
            model_name='raghul',
            name='MENGE_GR',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
