# Generated by Django 4.2.3 on 2024-05-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inte', '0004_raghul_menge_gr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raghul',
            name='MENGE_GR',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='raghul',
            name='MENGE_PO',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
