# Generated by Django 3.2.12 on 2024-06-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inte', '0008_user_groups_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCRResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('msgtxt', models.CharField(max_length=255)),
            ],
        ),
    ]
